# ###*B*###
#
# ERIKA Enterprise - a tiny RTOS for small microcontrollers
# 
# Copyright (C) 2002-2018 Evidence Srl
# 
# This file is part of ERIKA Enterprise.
# 
# See LICENSE file.
#
# ###*E*###

############################################################################
#
# This file is generated by RT-Druid.
# Please do not modify it.
#
############################################################################

############################################################################
#
# User options
#
############################################################################
OS_EE_OPT += OS_EE_VERBOSE
OS_EE_OPT += OSEE_DEBUG
OS_EE_OPT += OSEE_ASSERT
OS_EE_OPT += OS_EE_APPL_BUILD_DEBUG
OS_EE_OPT += OS_EE_BUILD_DEBUG
OS_EE_OPT += OSEE_API_EXTENSION


############################################################################
#
# Automatic options
#
############################################################################
OS_EE_OPT += OSEE_ARCH_TRICORE
OS_EE_OPT += OSEE_CPU_CLOCK (200000000U)
OS_EE_OPT += OSEE_EXTENDED_STATUS
OS_EE_OPT += OSEE_HAS_ALARMS
OS_EE_OPT += OSEE_HAS_AUTOSTART_TASK
OS_EE_OPT += OSEE_HAS_AUTOSTART_TRIGGER
OS_EE_OPT += OSEE_HAS_COUNTERS
OS_EE_OPT += OSEE_HAS_ERRORHOOK
OS_EE_OPT += OSEE_HAS_EVENTS
OS_EE_OPT += OSEE_HAS_IDLEHOOK
OS_EE_OPT += OSEE_HAS_ORTI
OS_EE_OPT += OSEE_HAS_SYSTEM_TIMER
OS_EE_OPT += OSEE_ISR2_MAX_HW_ASM_PRIO 2
OS_EE_OPT += OSEE_ISR2_MAX_PRIO (129U)
OS_EE_OPT += OSEE_MULTI_STACK
OS_EE_OPT += OSEE_OC_ECC2
OS_EE_OPT += OSEE_TASKING_CTC
OS_EE_OPT += OSEE_TC_2G
OS_EE_OPT += OSEE_TC_CORE0_ISR_MAX_PRIO  (2U)
OS_EE_OPT += OSEE_TC_CORE1_ISR_MAX_PRIO  (2U)
OS_EE_OPT += OSEE_TC_CORE2_ISR_MAX_PRIO  (2U)
OS_EE_OPT += OSEE_TC_TC39X
OS_EE_OPT += OS_EE_KERNEL_OSEK
OS_EE_OPT += OS_EE_RTD_BUILD_ENV_CYGWIN
OS_EE_OPT += OS_EE_RTD_DISABLE_OS_EE_OPT_DEFINES




############################################################################
#
# Path check and conversion
#
############################################################################
-include $(OS_EE_BASE_DIR)/mk/ee_path_helper.mk
-include $(ERIKA_FILES)/mk/ee_path_helper.mk

############################################################################
#
# TASKING CTC Compiler path
#
############################################################################
$(eval $(call check_and_set_cygwin_compiler_path,CCTCBIN,C:\Infineon\AURIX-Studio-1.8.0\plugins\com.infineon.aurix.tools_1.8.0\build_system\tools\Compilers\Tasking_1.1r8/ctc/bin/))


OSEE_TRICORE_MCU    := tc39x
OSEE_TRICORE_MCU_UC := TC39X
OSEE_TRICORE_STEP := AA

export OSEE_TRICORE_MCU
export OSEE_TRICORE_MCU_UC


############################################################################
#
# Flags
#
############################################################################
CFLAGS  +=
export CFLAGS

ASFLAGS +=
export ASFLAGS

LDFLAGS +=
export LDFLAGS

LDDEPS  +=
export LDDEPS

LIBS    +=
export LIBS


############################################################################
#
# Sources
#
############################################################################
OS_EE_CFG_SRCS +=
OS_EE_CFG_SRCS += ee_oscfg.c
export OS_EE_CFG_SRCS


############################################################################
#
# End
#
############################################################################

