/*
 * Generated by TASKING Pin Mapper for AURIX
 * - device  : TC38XPD
 * - package : LFBGA516
 */

/*
 * Instructions on how to build this generated file and the Infineon's iLLD library with the TASKING  VX-toolset
 * for TriCore:
 * 1. Provide appropriate include paths to the compiler (-I option) to locate the iLLD library.
 * 2. Provide macro IFX_CFG_USE_COMPILER_DEFAULT_LINKER to the compiler (-D option) to prevent multiple
 *    definitions of symbol '_START' (in cstart.c and IfxCpu_CStart0.c).
 * 3. Disable compiler option 'Automatic inclusion of .sfr files' (-H option) to prevent macros to be redefined.
 */

#ifndef AURIX_PIN_MAPPINGS_H_
#define AURIX_PIN_MAPPINGS_H_

/* Infineon's iLLD library include files */

#include <Port/Io/IfxPort_Io.h>

#include <_PinMap/IfxPort_PinMap.h>


/* Generic alternate I/O configuration */

// can0_node0
#define IFXCFG_P20_7_IO_CONFIG                  { &IfxPort_P20_7, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P20_8_IO_CONFIG                  { &IfxPort_P20_8, IfxPort_Mode_outputPushPullAlt5, IfxPort_PadDriver_cmosAutomotiveSpeed4 }


/* Initialization routines */

extern void can0_node0_init_pins(void);


#endif /* AURIX_PIN_MAPPINGS_H_ */
