/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxCan_Can.h"
#include "IfxCan.h"
IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

#define TESTED_NODES 2
#define NODE0_RAM_OFFSET 0x0
#define NODE1_RAM_OFFSET 0x1000
// CAN handle
IfxCan_Can can;

// CAN Node handles
IfxCan_Can_Node canNode[TESTED_NODES];

// data buffers
uint32 txData[2];
uint32 rxData[2];


IfxCan_Can_NodeConfig nodeConfig_rx;
IfxCan_Can_NodeConfig nodeConfig_tx;

void Can_Init(void);
void config_rx_node(IfxCan_Can_NodeConfig nodeConfig);
void config_tx_node(IfxCan_Can_NodeConfig nodeConfig);

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    
    while(1)
    {
    }
}

void Can_Init(void)
{
   // create module configuration
   IfxCan_Can_Config canConfig;
   IfxCan_Can_initModuleConfig(&canConfig, &MODULE_CAN0);

   // choose the interrupt groups configuration
   // Tx interrupts
   canConfig.traco.priority = 10;
   canConfig.traco.typeOfService = IfxSrc_Tos_cpu0;
   canConfig.traco.interruptLine = IfxCan_InterruptLine_0;

   // Rx interrupts
   canConfig.reint.priority = 11;
   canConfig.reint.typeOfService = IfxSrc_Tos_cpu0;
   canConfig.reint.interruptLine = IfxCan_InterruptLine_1;
   canConfig.can->

   IfxCan_Can_initModule(&can, &canConfig);

   // create node configuration

   // Node 0 as receive node
   {
       IfxCan_Can_NodeConfig nodeConfig;
       IfxCan_Can_initNodeConfig(&nodeConfig, &can);

       // initialize Node 0
       nodeConfig.nodeId = IfxCan_NodeId_0;
       nodeConfig.clockSource = IfxCan_ClockSource_both;

       nodeConfig.frame.type = IfxCan_FrameType_receive;

       nodeConfig.filterConfig.standardListSize = 2;

       nodeConfig.messageRAM.standardFilterListStartAddress = 0x100;
       nodeConfig.messageRAM.rxBuffersStartAddress          = 0x200;
       nodeConfig.messageRAM.baseAddress                    = MODULE_CAN0_RAM + NODE0_RAM_OFFSET;

    // enable the required interrupts with respective to group interrupts configuration at module level
    nodeConfig.interruptConfig.messageStoredToDedicatedRxBufferEnabled = TRUE;

       // initialize Node 0
       IfxCan_Can_initNode(&canNode[0], &nodeConfig);
   }

   // Node 1 as transmit node
   {
       IfxCan_Can_NodeConfig nodeConfig;
       IfxCan_Can_initNodeConfig(&nodeConfig, &can);

       nodeConfig.nodeId = IfxCan_NodeId_1;
       nodeConfig.clockSource = IfxCan_ClockSource_both;

       nodeConfig.frame.type = IfxCan_FrameType_transmit;

       nodeConfig.txConfig.dedicatedTxBuffersNumber = 2;

       nodeConfig.messageRAM.txBuffersStartAddress = 0x400;
       nodeConfig.messageRAM.baseAddress           = MODULE_CAN0_RAM + NODE1_RAM_OFFSET;

    // enable the required interrupts with respective to group interrupts configuration at module level
    nodeConfig.interruptConfig.transmissionCompletedEnabled = TRUE;

       // initialize Node 1;
       IfxCan_Can_initNode(&canNode[1], &nodeConfig);
   }
}
void config_tx_node(IfxCan_Can_NodeConfig nodeConfig){

}
void config_rx_node(IfxCan_Can_NodeConfig nodeConfig){

}




