/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "can_control.h"
#include "bsp.h"
IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

#define TESTED_NODES 2
#define NODE0_RAM_OFFSET 0x0
#define NODE1_RAM_OFFSET 0x1000

#define TIME_TO_WAIT 1000

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    can_init();

    uint8 data_length = 4;
    //Creating data set tp send
    uint8 data_to_transfer[MAXIMUM_CAN_FD_DATA_PAYLOAD];
    data_to_transfer[0] = (uint8)0xFF;
    data_to_transfer[1] = (uint8)0xAA;
    data_to_transfer[2] = (uint8)0xBB;
    data_to_transfer[3] = (uint8)0xCC;


    //configuring a message to send
    IfxCan_Message msg;
    can_FD_messages_enum message_type = 2;
    IfxCan_Can_initMessage(&msg);
    msg.messageId = can_fd_messages[message_type].messageId;
    msg.messageIdLength = can_fd_messages[message_type].messageIdLength;
    msg.frameMode = can_fd_messages[message_type].frameMode;
    msg.dataLengthCode = can_fd_messages[message_type].messageLen;

    while(1)
    {
        waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, TIME_TO_WAIT));

        can_transmit_message(msg, &data_to_transfer, data_length);
        //if(is_new_message_recieved == TRUE)
        //{
            can_recieved_message_show(1);
            is_new_message_recieved = FALSE;
        //}


    }
}





