/**********************************************************************************************************************
 * \file Blinky_LED.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Port/Std/IfxPort.h"
//#include "Bsp.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define LED_D107    &MODULE_P15,0                                           /* LED D107: Port, Pin definition       */
#define LED_RESET   &MODULE_P34,4                                           /* LED D107: Port, Pin definition       */
#define LED_PWDN    &MODULE_P11,15                                           /* LED D107: Port, Pin definition       */
#define WAIT_TIME   500                                                     /* Wait time constant in milliseconds   */
#define RXD2        &MODULE_P11,8
#define RXD1        &MODULE_P11,9
#define RDX0        &MODULE_P11,10
#define RCTL        &MODULE_P11,11
#define RXCLK       &MODULE_P11,12
#define TXD3        &MODULE_P11,0
#define TXD2        &MODULE_P11,1
#define TXD1        &MODULE_P11,2
#define TXD0        &MODULE_P11,3
#define TXCLK       &MODULE_P11,4
#define REFCLK      &MODULE_P11,5
#define TCTL        &MODULE_P11,6
#define RXD3        &MODULE_P11,7

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* This function initializes the port pin which drives the LED */
void initLED(void)
{
    /* Initialization of the LED used in this example */
    IfxPort_setPinModeOutput(LED_D107, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
//    IfxPort_setPinModeOutput(LED_RESET, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeInput(LED_PWDN, IfxPort_InputMode_pullUp);
    IfxPort_setPinModeInput(LED_RESET, IfxPort_InputMode_pullUp);
    IfxPort_setPinModeInput(RXD2, IfxPort_InputMode_noPullDevice);
    IfxPort_setPinModeInput(RXD1, IfxPort_InputMode_noPullDevice);
    IfxPort_setPinModeInput(RDX0, IfxPort_InputMode_noPullDevice);
    IfxPort_setPinModeInput(RCTL, IfxPort_InputMode_noPullDevice);
    IfxPort_setPinModeInput(RXCLK, IfxPort_InputMode_noPullDevice);
    IfxPort_setPinModeInput(TXD3, IfxPort_InputMode_noPullDevice);
    IfxPort_setPinModeInput(TXD2, IfxPort_InputMode_noPullDevice);
    IfxPort_setPinModeInput(TXD1, IfxPort_InputMode_noPullDevice);
    IfxPort_setPinModeInput(TXD0, IfxPort_InputMode_noPullDevice);
    IfxPort_setPinModeInput(TXCLK, IfxPort_InputMode_noPullDevice);
    IfxPort_setPinModeInput(REFCLK, IfxPort_InputMode_noPullDevice);
    IfxPort_setPinModeInput(TCTL, IfxPort_InputMode_noPullDevice);
    IfxPort_setPinModeInput(RXD3, IfxPort_InputMode_noPullDevice);


//    IfxPort_setPinModeOutput(LED_PWDN, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
//    IfxPort_setPinModeOutput(LED_PWDN, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);

    /* Switch OFF the LED (low-level active) */
    IfxPort_setPinHigh(LED_D107);
//    IfxPort_setPinHigh(LED_RESET);
//    IfxPort_setPinHigh(LED_PWDN);
}

/* This function toggles the port pin and wait 500 milliseconds */
void blinkLED(void)
{
    IfxPort_togglePin(LED_D107);                                                /* Toggle the state of the LED      */
//    IfxPort_togglePin(LED_RESET);
//    IfxPort_togglePin(LED_PWDN);

    //waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME));    /* Wait 500 milliseconds            */


}
